### ISSUE TITLE
Enhancement request:  beginning to end example of use

### ISSUE THREAD

**Issue by udf2457** [auraphp/Aura.Router#122] opened 2016-05-26 16:04 UTC
In the documentation code snippets, your variable assignment is not always clear, for example: 

> Then call the match() method to match a PSR-7 ServerRequestInterface instance to a mapped Route.
> <?php
> $route = $matcher->match($request);
> ?>

Great, but where does $request come from ? 

It would be nice if you could show a basic "real-world" type example from start to finish.  Would be easier to get a feel for how things work rather than a bunch of text interspersed with code snippets and its left to the reader to figure out how what goes where/how/when.

**Comment by harikt** [comment] 2016-05-26 16:12
Duplicate of #113 . Solution is provided in comment  https://github.com/auraphp/Aura.Router/issues/113#issuecomment-217751304 .

For the sake of easy reference 
1. Download https://zendframework.github.io/zend-diactoros
2. You can create request object as  

``` php
$request = Zend\Diactoros\ServerRequestFactory::fromGlobals(
    $_SERVER,
    $_GET,
    $_POST,
    $_COOKIE,
    $_FILES
);
```

See diactoros for more documentation how to use it.

Closing the same. In case more questions you can comment here on related thread.

**Closed as completed by harikt** 2016-05-26 16:12 UTC

**Comment by harikt** [comment] 2016-05-26 16:15
You can also see a working example : https://github.com/thinsoldier/aura-router-test/blob/5791643157fc4398170a373c823f21c6cd98cb25/index.php . Taken from issue #119 .
