### ISSUE TITLE
Wildcard routes

### ISSUE THREAD

**Issue by calvinfroedge** [auraphp/Aura.Router#15] opened 2012-11-05 21:11 UTC
Hi,

Are wildcard routes supported?  ie /post/\* where \* could be 1 to n params.

Great router!

**Comment by pmjones** [comment] 2012-11-05 21:28
The short answer is "no." The longer answer is "not yet, depending on what you think it should work like."  The problem is, the values extracted are currently in key-value pairs (named params). With a "*" notation (or an explicit '{:params}' notation) the resulting extractions would have to be numeric instead of named. Thoughts?

**Comment by calvinfroedge** [comment] 2012-11-05 21:33
{:*} or {:params} works for me.  What existing methods do I need to focus on to implement this?

**Comment by pmjones** [comment] 2012-11-05 21:38
While we're here, something to think about: we can either use sequential values, or we can collect all the wildcarded params under their own name.

Given a route of '/post/{:id}/_' and a path of '/post/88/foo/bar/baz', the former variation nets us ['id' => '88', 0 => 'foo', 1 => 'bar', 2 => 'baz'].  The latter variation nets us ['id' => '88', '_' => ['foo', 'bar', 'baz']].  I can see strengths and weaknesses for both.  Thoughts?

**Comment by pmjones** [comment] 2012-11-05 21:43
The methods to concentrate on, regardless, would be Aura\Router\Route::setRegex() and isRegexMatch(), as well as generate() to create paths from an array of data.  I say we go with {:*} as the notation; we'll need some customized logic in there to extract things properly, given our current concentration on names.  If/when you send a pull request, please do so against 'develop' and not 'master'.

**Comment by pmjones** [comment] 2012-11-05 21:44
Oh, and appropriate test cases as well please. :-)

**Comment by pmjones** [comment] 2012-11-05 21:45
And FWIW i'm not ideologically attached to {:_}; you may discover just '_' is easier and more sensible. I bow to actual observation and usage.

**Comment by calvinfroedge** [comment] 2012-11-05 23:21
My intuition prompted me to try *, and I like the idea of \* yielding [].  10-4, test cases and whatnot.

**Comment by pmjones** [comment] 2012-11-05 23:22
Good man!  Looking forward to seeing the results.

**Comment by calvinfroedge** [comment] 2012-11-06 00:10
Ok...trying to implement this.  Brain puzzle so far.

**Comment by pmjones** [comment] 2012-11-06 00:13
Seems like there would be a check to see if the route string ends in "/_" first thing, and convert it to a regular expression named '_' or '**params**' or something obvious. Then on matching, look for a '*' value, and explode on slashes to make an array for that value.

**Comment by calvinfroedge** [comment] 2012-11-07 07:56
Maybe I'm approaching this wrong, but I'm 3 hours in and still no cigar.  Still, far enough along to ask a few questions.  Sorry I'm mucking this up.  On 347 I'm checking if it's a wildcard and if so setting a pattern to use.  On 372 I'm ensuring that regex pattern (I still can't decipher how the ?P works) for catching all is still applied.

338     protected function setRegex()
339     {
340         // first, extract inline token params from the path
341         $find = "/{:(._?)(:(._?))?}/";
342         preg_match_all($find, $this->path, $matches, PREG_SET_ORDER);
343         foreach ($matches as $match) {
344             $whole = $match[0];
345             $name  = $match[1];
346 
347             if($name == '_'){
348               $this->params[$name] = "(._)";
349             } elseif (isset($match[3])) {
350                 // there is an inline token pattern; retain it, overriding
351                 // the existing param ...
352                 $this->params[$name] = $match[3];
353                 // ... and replace in the path without the pattern.
354                 $this->path = str_replace($whole, "{:$name}", $this->path);
355             } elseif (! isset($this->params[$name])) {
356                 // use a default pattern when none exists
357                 $this->params[$name] = "([^/]+)";
358             }
359         }
360 
361         // now create the regular expression from the path and param patterns
362         $this->regex = $this->path;
363         if ($this->params) {
364             $keys = [];
365             $vals = [];
366             foreach ($this->params as $name => $subpattern) {
367                 if ($subpattern[0] != '(') {
368                     $message = "Subpattern for param '$name' must start with '('.";
369                     throw new Exception($message);
370                 } else {
371                     $keys[] = "{:$name}";
372                     if($name = "*"){
373                         $vals[] = "(" . substr($subpattern, 1);
374                     } else {
375                         $vals[] = "(?P<$name>" . substr($subpattern, 1);
376                     }
377                 }
378             }
379             $this->regex = str_replace($keys, $vals, $this->regex);
380         }
381     }

So first, is that approach in the realm of possibility or is it too simplistic?

Second, when I get around to matching:

392     protected function isRegexMatch($path)
393     {
394         $toMatch = "#^{$this->regex}$#";
395         $match = preg_match($toMatch, $path, $this->matches);
396         if (! $match) {
397             $this->debug[] = 'Not a regex match.';
398         }
399         return $match;
400     }

Given a route like http://aura.router/foo/1/baz/bop/

My match array will look like:

array(3) { [0]=> string(15) "/foo/1/baz/bop/" [1]=> string(1) "1" [2]=> string(7) "baz/bop" }

...Where do I go next?

On my end it feels like I'm mucking around with something I don't quite understand well enough and I'm making the laziest, shoddiest implementation possible given my poor understanding.  So, sorry for you needing to waste time on my incompetence, I would like to understand and contribute to this fantastic fucking piece of code.

**Comment by pmjones** [comment] 2012-11-07 14:27
No problem dude. WHen you mentioned it, it went into my brain and has been poking at me since. I'll take a look later and see if I can help.

**Comment by pmjones** [comment] 2012-11-07 16:23
@calvinfroedge Meanwhile, write up some tests that show the behavior you expect to see.

**Comment by pmjones** [comment] 2012-11-07 17:06
I have implemented and pushed in 'develop' branch. Essentially:
1. In `setRegex()`, we take any path ending with `"/*"` and replace it with `"/{:__wildcard__:(.*)"`.
2. In `isMatch()`, when building values, we remove `['__wildcard__']` and replace it with `['*']`, using the exploded values of `__wildcard__`.

Let me know if that does the trick for you.

**Comment by pmjones** [comment] 2012-11-07 17:15
Now, a question: given a route of '/foo/*', it will match '/foo/bar'.  It will also match '/foo/' (with a trailing slash).  But, should it also match '/foo' (no trailing slash) ?

**Comment by calvinfroedge** [comment] 2012-11-07 19:52
Ok, this makes sense.  I think this covers my use case.  I'm going to start using it and will let you know if I have any problems.  Sorry, I think I was focusing too much on the regex.  Now that I see how simple your solution is I feel like a dunce = ).

**Comment by harikt** [comment] 2012-11-08 00:53
hm, I too tried . But didn't worked :-1:  . Nice to see the implementation @pmjones . Thank you for bringing this @calvinfroedge .

**Comment by harikt** [comment] 2012-11-20 15:39
@pmjones can we close the issue?

**Comment by pmjones** [comment] 2012-11-20 15:59
@calvinfroedge Are you satisfied with the solution?

**Comment by pmjones** [comment] 2012-11-23 19:43
Closing this, pending further comment from the interested parties.

**Closed as completed by pmjones** 2012-11-23 19:43 UTC
